# Generated by Django 6.0.2 on 2026-04-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.CharField(blank=True, help_text='Например: img/products/-24.jpg', max_length=255, verbose_name='Путь к картинке'),
        ),
    ]
