FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir --use-deprecated=legacy-resolver -r requirements.txt
COPY . .


EXPOSE 8000

CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "our_project.asgi:application"]
