name: Django CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    # Это указывает GitHub Actions выполнять ВСЕ команды внутри папки our_project
    defaults:
      run:
        working-directory: ./our_project

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: pinkstore_test
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: adminpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      # Этот шаг всегда выполняется в корне репозитория (не меняйте его)
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: our_project.settings
          DB_HOST: localhost
          DB_NAME: pinkstore_test
          DB_USER: admin
          DB_PASSWORD: adminpassword
          REDIS_HOST: localhost
        run: |
          pytest -v
